"""empty message

Revision ID: 253cc9a1fee0
Revises: 
Create Date: 2020-04-01 17:56:45.627961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253cc9a1fee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('btn_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('btn_text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
